### ISSUE TITLE
Modelagem do Banco

### ISSUE THREAD

**Issue by ernegreiros** [ernegreiros/BatalhaNaval#1]
Necessário discutir e implementar a modelagem do banco de dados que será utilizado

**Comment by PePires58** [comment]
Vamos ir criando sob demanda, beleza?

**Comment by ernegreiros** [comment]
CREATE DATABASE battleship;

CREATE TABLE Users(
    ID int NOT NULL,
    Name varchar(255) NOT NULL,
    Login varchar(30) NOT NULL
    Senha varchar(30) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Match(
    ID int NOT NULL,	
    player1 int NOT NULL,
    player2 int NOT NULL,
	status int NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (player1) REFERENCES Users(ID),
    FOREIGN KEY (player2) REFERENCES Users(ID),
);

CREATE TABLE BattleField(
    ID int NOT NULL,
    player int NOT NULL,	
    posX int NOT NULL,
    posY int NOT NULL,
    Ship int NOT NULL,
    MatchId int NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (player) REFERENCES Users(ID),
        FOREIGN KEY (MatchId) REFERENCES Match(ID),
        FOREIGN KEY (Ship) REFERENCES Ships(ID)
);

**Comment by PePires58** [comment]
Encerrar issue.

**Comment by PePires58** [comment]
CREATE TABLE NAVIOS(
   ID INT,
   NOME VARCHAR(30),
   QTDE_COOR INT /*Quantidade de coordenadas*/
)

CREATE TABLE NAVIOS_IMAGEM(
   ID_NAVIO INT,
   BLOB IMAGEM
)

Incluir na tabela de BattleField o ID do navio que está naquele coordenada.

**Comment by ltakato** [comment]
> CREATE TABLE NAVIOS(
> ID INT,
> NOME VARCHAR(30),
> QTDE_COOR INT /_Quantidade de coordenadas_/
> )
> 
> CREATE TABLE NAVIOS_IMAGEM(
> ID_NAVIO INT,
> BLOB IMAGEM
> )
> 
> Incluir na tabela de BattleField o ID do navio que está naquele coordenada.

@PePires58 como voce imagina ter as coordenadas com as imagens? ou é diferente a ideia?

**Comment by ltakato** [comment]
@PePires58 transcrevendo o que tu disse:

Navio com 3 coordenadas.
Par 1: Frente do navio 
Par 2: Meio do navio
Par 3: Fim do navio.

É apenas para o front saber qual imagem pegar. Entendeu? É apenas visual. Não impacta na jogabilidade

Daí no cadastro: [Nome do navio]_parte1.png

Daí vc consegue saber qual imagem pegar pra rendenizar em cada "quadrado" na zona de guerra no batalha naval

Da pra colocar uma tabela de temas e lincar os navios aos temas (luz, trevas etc)

**Comment by ltakato** [comment]
@PePires58 sinceramente esse de imagens não achei tão interessante. já dos temas me parece interessante!!

**Comment by PePires58** [comment]
@ltakato , Certo! Então manteríamos apenas a tabela de navios e bola pra frente?

**Comment by PePires58** [comment]
@ernegreiros 
CREATE TABLE ShipsThemes(
    ID INT NOT NULL,
    NAME VARCHAR(30)
    PRIMARY KEY(ID)
)

CREATE TABLE Ships(
   ID INT,
   NAME VARCHAR(30),
   THEME INT,
   PRIMARY KEY (ID)
   FOREIGN KEY (THEME) REFERENCES ShipsThemes(ID),
)

**Comment by PePires58** [comment]
@ltakato @ernegreiros 
CREATE DATABASE battleship;

CREATE TABLE Users(
ID int NOT NULL,
Name varchar(255) NOT NULL,
Login varchar(30) NOT NULL
Senha varchar(30) NOT NULL,
Money float NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Match(
ID int NOT NULL,
player1 int NOT NULL,
player2 int NOT NULL,
status int NOT NULL,
currentPlayer int not null, /*Usado para identificar de quem é a vez, possibilitando utilizar o poder*/
winner int NULL, /*Identificar quem ganhou e gerar dinheiro*/
PRIMARY KEY (ID),
FOREIGN KEY (player1) REFERENCES Users(ID),
FOREIGN KEY (player2) REFERENCES Users(ID),
);

CREATE TABLE BattleField(
ID int NOT NULL,
player int NOT NULL,
posX int NOT NULL,
posY int NOT NULL,
MatchId int NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (player) REFERENCES Users(ID),
FOREIGN KEY (MatchId) REFERENCES Match(ID),
FOREIGN KEY (Ship) REFERENCES Ships(ID)
);

CREATE TABLE SpecialPowers(
    ID int not null,
    Name varchar(30) not null,
    Cost float not null,
    Quantifier int not null,
    Type int not null,
    Compensation float not null default 0,
    PRIMARY KEY (ID)
);

/*Essa tabela sera gerada em conjunto com a partida, sendo gerada uma carga de acordo com os poderes especiais que o jogador selecionou*/
CREATE TABLE MatchSpecialPowers(
    MatchId int not null,
    Player int not null,
    SpecialPowerId int not null,
    Used bit not null default 0 /*Identificar se já usou o poder*/
);

**Comment by ernegreiros** [comment]
CREATE TABLE Users(
ID int IDENTITY(1,1) PRIMARY KEY,
Name varchar(255) NOT NULL,
Login varchar(30) NOT NULL,
Password varchar(30) NOT NULL,
Code varchar(30) Not null,
Money float NOT NULL,
);

CREATE TABLE Match(
ID int IDENTITY(1,1) PRIMARY KEY,
Player1 int NOT NULL,
Player2 int NOT NULL,
Status int NOT NULL,
CurrentPlayer int not null,
Winner int NULL, 
FOREIGN KEY (Player1) REFERENCES Users(ID),
FOREIGN KEY (Player2) REFERENCES Users(ID),
);


CREATE TABLE BattleField(
ID int IDENTITY(1,1) PRIMARY KEY,
PlayerId int NOT NULL,
PosX int NOT NULL,
PosY int NOT NULL,
MatchId int NOT NULL,
FOREIGN KEY (PlayerId) REFERENCES Users(ID),
FOREIGN KEY (MatchId) REFERENCES Match(ID),
);


CREATE TABLE SpecialPowers(
ID int IDENTITY(1,1) PRIMARY KEY,
Name varchar(30) not null,
Cost float not null,
Quantifier int not null,
Type int not null,
Compensation float not null default 0,
);

CREATE TABLE MatchSpecialPowers(
ID int IDENTITY(1,1) PRIMARY KEY,
MatchId int not null,
PlayerId int not null,
SpecialPowerId int not null,
Used bit not null default 0 
);

**Comment by ernegreiros** [comment]
-- Criar Tabelas
CREATE TABLE Users(
ID int IDENTITY(1,1) PRIMARY KEY,
Name varchar(255) NOT NULL,
Login varchar(30) NOT NULL,
Password varchar(30) NOT NULL,
Code varchar(30) Not null,
Money float NOT NULL,
);

CREATE TABLE Match(
ID int IDENTITY(1,1) PRIMARY KEY,
Player1 int NOT NULL,
Player2 int NOT NULL,
Status int NOT NULL,
CurrentPlayer int not null,
Winner int NULL,
FOREIGN KEY (Player1) REFERENCES Users(ID),
FOREIGN KEY (Player2) REFERENCES Users(ID),
);

CREATE TABLE BattleField(
ID int IDENTITY(1,1) PRIMARY KEY,
PlayerId int NOT NULL,
PosX int NOT NULL,
PosY int NOT NULL,
MatchId int NOT NULL,
FOREIGN KEY (PlayerId) REFERENCES Users(ID),
FOREIGN KEY (MatchId) REFERENCES Match(ID),
);

CREATE TABLE SpecialPowers(
ID int IDENTITY(1,1) PRIMARY KEY,
Name varchar(30) not null,
Cost float not null,
Quantifier int not null,
Type int not null,
Compensation float not null default 0,
);

CREATE TABLE MatchSpecialPowers(
ID int IDENTITY(1,1) PRIMARY KEY,
MatchId int not null,
PlayerId int not null,
SpecialPowerId int not null,
Used bit not null default 0
);

CREATE TABLE Themes(
ID int IDENTITY(1,1) PRIMARY KEY,
Name varchar(30) not null,
Description varchar(100) not null,
ImagePath varchar(200) NOT NULL
);

CREATE TABLE Ships(
ID int IDENTITY(1,1) PRIMARY KEY,
Name varchar(30) not null,
Type int not null,
ImagePath varchar(200) NOT NULL,
ThemeId int not null,
FOREIGN KEY (ThemeId) REFERENCES Themes(ID)
);

--Deletar Tabelas
/*
DROP TABLE Ships

DROP TABLE Themes

DROP TABLE MatchSpecialPowers

DROP TABLE SpecialPowers

DROP TABLE BattleField

DROP TABLE Match

DROP TABLE Users
*/

**Comment by PePires58** [comment]
> -- Criar Tabelas
> CREATE TABLE Users(
> ID int IDENTITY(1,1) PRIMARY KEY,
> Name varchar(255) NOT NULL,
> Login varchar(30) NOT NULL,
> Password varchar(30) NOT NULL,
> Code varchar(30) Not null,
> Money float NOT NULL,
> );
> 
> CREATE TABLE Match(
> ID int IDENTITY(1,1) PRIMARY KEY,
> Player1 int NOT NULL,
> Player2 int NOT NULL,
> Status int NOT NULL,
> CurrentPlayer int not null,
> Winner int NULL,
> FOREIGN KEY (Player1) REFERENCES Users(ID),
> FOREIGN KEY (Player2) REFERENCES Users(ID),
> );
> 
> CREATE TABLE BattleField(
> ID int IDENTITY(1,1) PRIMARY KEY,
> PlayerId int NOT NULL,
> PosX int NOT NULL,
> PosY int NOT NULL,
> MatchId int NOT NULL,
> FOREIGN KEY (PlayerId) REFERENCES Users(ID),
> FOREIGN KEY (MatchId) REFERENCES Match(ID),
> );
> 
> CREATE TABLE SpecialPowers(
> ID int IDENTITY(1,1) PRIMARY KEY,
> Name varchar(30) not null,
> Cost float not null,
> Quantifier int not null,
> Type int not null,
> Compensation float not null default 0,
> );
> 
> CREATE TABLE MatchSpecialPowers(
> ID int IDENTITY(1,1) PRIMARY KEY,
> MatchId int not null,
> PlayerId int not null,
> SpecialPowerId int not null,
> Used bit not null default 0
> );
> 
> CREATE TABLE Images(
> ID int IDENTITY(1,1) PRIMARY KEY,
> Name varchar(30) not null,
> Path varchar(30) not null
> );
> 
> CREATE TABLE Themes(
> ID int IDENTITY(1,1) PRIMARY KEY,
> Name varchar(30) not null,
> Description varchar(100) not null,
> ImageId int NOT NULL,
> FOREIGN KEY (ImageId) REFERENCES Images(ID)
> );
> 
> CREATE TABLE Ships(
> ID int IDENTITY(1,1) PRIMARY KEY,
> Name varchar(30) not null,
> Type int not null,
> ImageId int NOT NULL,
> ThemeId int not null,
> FOREIGN KEY (ImageId) REFERENCES Images(ID),
> FOREIGN KEY (ThemeId) REFERENCES Themes(ID)
> );
> 
> --Deletar Tabelas
> /*
> DROP TABLE Ships
> 
> DROP TABLE Themes
> 
> DROP TABLE Images
> 
> DROP TABLE MatchSpecialPowers
> 
> DROP TABLE SpecialPowers
> 
> DROP TABLE BattleField
> 
> DROP TABLE Match
> 
> DROP TABLE Users
> */

@ernegreiros , 
1)na tabela de player, qual a diferença entre password e code?
2)Por que na tabela de barco tem o id da imagem? Seria algo de 1->N, certo? então, uma tabela que faça esse relacionamento.
3) Precisamos um atributo na tabela de player para identificar o tipo de usuário (super - S, usuario - U)

**Comment by ernegreiros** [comment]
1) code, vai ser usado pra identificação no websocket
2) Não entendi a sua duvida, cada barco tem 1 imagem, é um relacionamento 1 -> N onde N fica na tabela barcos 
3) A identificação de super usuario não vai ser feita pelo login e senha dele? pq um campo a mais

**Comment by ernegreiros** [comment]
Comentario com script atualizado

**Comment by ernegreiros** [comment]
Fechando essa issue para usarmos a https://github.com/ernegreiros/BatalhaNaval/issues/48
