### ISSUE TITLE
Vamos inovar com Tema? (Sim? Não? Sugestões?)

### ISSUE THREAD

**Issue by ltakato** [ernegreiros/BatalhaNaval#10]
Pessoal, de qualquer forma o professor está exigindo que tenha algum diferencial.
Dentre as ideias que andamos discutindo, um dos que achamos mais simples sem afetar tanto na mecânica (que é o mais difícil) foi inovar em temas: em vez de fazer com Navios, fazer com outra tematica (mitologia, medieval, etc).
O que acham da proposta? Concordam? Sugestões?

**Comment by cchen7bf** [comment]
poderia ser de monstros marinho

**Comment by PePires58** [comment]
Concordo, navios de tema Luz, escuridão, medial etc.
Daria para criar uma tabela com esses temas e ir amarrando os navios cadastrados com seus respectivos temas.

**Comment by julianababilon** [comment]
Gostei do tema do cristian pq nem precisaria mudar o nome do jogo, acredito que ao invés de só navios com nomes diferentes poderíamos ter os próprios monstros ( https://www.google.com.br/amp/s/myanimals.com/pt/5-monstros-marinhos-e-suas-historias/amp/ ) 
Uma jogabilidade que pode ser alterada sem muito esforço (acredito eu) é quando o navio é atingido já da game over pra pessoa. (no caso seria 5 monstros e 1 navio)

**Comment by julianababilon** [comment]
Isso do jogo acabar mais rápido e tb desse fator medo da pessoa de cara acertar seu navio pode deixar o jogo mais interessante. Não sei se vocês jogaram batalha naval nos últimos tempos, é bem chatinho :(

**Comment by ltakato** [comment]
sugestão do Luiz Antonio:

"As pessoas em geral gostam de misterio , terror e super-heroi (exemplos). Pode ser uma batalha de monstros e super-herois, tambem pensei em aventura: caça a brucha ou monstros...."

**Comment by PePires58** [comment]
Sugiro que crie os temas a partir de um CRUD e depois a pessoa escolhe o tema e front mostra. @ltakato

**Comment by ltakato** [comment]
Ideia que estamos cogitando: possibilitar compra de "peças/personagens" (a definir o nome). exemplos: monstros marinhos, herois, pokemons...

**Comment by ltakato** [comment]
Ideia do Eric: ter personagens de guerra: soldados, etc que nem age of empires pra ficar mais simples

**Comment by ltakato** [comment]
Outra ideia: tiros especiais que voce pode comprar (que pode atingir uma cruz, quatro quadrados, 3 quadrados). Que podem ser usado apenas algumas vezes! Definir: cada usuario pode usar apenas x poderes desse por partida. E outros especiais tambem mais relacionada a "suporte": recuperar quadrados, revelar quadrados do adversario

Sugestoes de poderes:
- ataque: atingir x quadrados
- suporte: revelar uma area x, "ignorar/proteger" uma regiao por uma rodada..., recuperar um dano atingido

**Comment by ltakato** [comment]
Sugestao da Juliana: em vez de "comprar" poderes e guardar e usar em partidas, voce sempre ir gastando nas partidas mesmo (voce ganhou essa, na proxima, voce vai gastar de novo pra usar os poderes)

**Comment by ltakato** [comment]
Como não vamos mais inovar no "tema" do jogo, e sim mais em sugesoes de "poderes", vamos fechar essa issue! (vou abrir uma outra)
