### ISSUE TITLE
Vamos tentar inovar com a possibilidade de "Comprar" os componentes do jogo? Sim? Não? Sugestões?

### ISSUE THREAD

**Issue by ltakato** [ernegreiros/BatalhaNaval#11]
Pessoal, uma das coisas que foi levantada (inclusive pelo professor), é a possibilidade do usuário conseguir "comprar" componentes (seja navio, ou de qualquer outro tematica que a gente definir). Já aproveitando para cobrir também a parte de "monetizar" com projeto.
Vale lembrar que caso avance com essa ideia, tambem tem que contemplar a parte da "compra" do usuario (se vai ter moeda virtual dentro do jogo, ou se toda vez que usuario for comprar a gente "simula" uma transação).
OBS: de qualquer forma, eu acho que seria muito forçado ter integração com pagamento, para um projeto de "faculdade", acho que por ora seria mais apenas "simular" mesmo (fingir que pagou, apenas colocando numeros, valores)

**Comment by PePires58** [comment]
Eu acho que a parte de pagamento é muito forçado para faculdade também! Visto que necessidade de transação em ambas as partes, cadastro das contas, integração com API de pagamentos e etc.
Qual seria sua sugestão para "Simular"?

Uma maneira da gente realizar isso, seria iniciar o jogo com uma grana fixa, por exemplo: 1000 reais, e então o cara escolhe oque quer pegar em cada partida e pau no gato.
Dai pode ser acumulativo, cada partida que ganha, ganha 100 reais, dai ele vai comprando os itens para ele, mas dai já entra na ideia de evolução de nível para manter o jogo justo...

Oque acha?

**Comment by julianababilon** [comment]
@⁨Leonardo Takato Fatec⁩ sobre a questão da monetização acredito que podemos fingir e usar ela só para “vender” o projeto mesmo, mas não necessariamente precisará ter essa funcionalidade no programa que iremos entregar... E sim num slide as opções de compra e como funcionaria

**Comment by julianababilon** [comment]
sobre a ideia da pontuação do @⁨Pedro Henrique Fatec⁩  eu não sei se entendi direito, no final aqueles 1000 reais acabariam e ele teria com comprar (com dinheiro de verdade) mais créditos para poder ter mais itens? pra continuar jogando? Talvez funcionaria melhor com uma ideia de ranking... A ideia da compra poderia ser só para comprar “navios” (ou qualquer que seja o tema) melhores e assim subir no ranking, talvez essa competição de estar entre os 1000, 100, 10 melhores faça com que o usuário jogue mais e acabe comprando mais itens, ou da própria competição entre amigos pra ver quem está em melhor posição

**Comment by PePires58** [comment]
@julianababilon , a ideia é 1000 reais (moeda do jogo), ou seja, vai evoluindo e ganhando mais dinheiro do jogo, sem tocar na parte monetária propriamente dita.

**Comment by ernegreiros** [comment]
Vai ser feito 
https://github.com/ernegreiros/BatalhaNaval/issues/10#issuecomment-701111392
