### ISSUE TITLE
[API] - Disponibilizar método para criar partida

### ISSUE THREAD

**Issue by PePires58** [ernegreiros/BatalhaNaval#12]
Será disponibilizado uma rota para iniciar a partida:
Rota: api/Match/CreateMatch
Nome objeto do parâmetro: pModel
**Objeto de entrada:** 
<table>
<thead>
<tr>
<th>Nome da propriedade</th>
<th>Tipo de campo</th>
<th>Obrigatório?</th>
</tr>
<tbody>
<tr>
<td>Player1</td>
<td>Int</td>
<td>SIM</td>
</tr>
<tr>
<td>Player2</td>
<td>Int</td>
<td>SIM</td>
</tr>
</tbody>
</table>

Objeto de retorno, quando sucesso:
<table>
<thead>
<tr>
<th>Nome da propriedade</th>
<th>Tipo de campo</th>
</tr>
<tbody>
<tr>
<td>ID</td>
<td>Int</td>
</tr>
<tr>
<td>Message</td>
<td>String</td>
</tr>
<tr>
</tbody>
</table>

**Comment by PePires58** [comment]
@ernegreiros, @ltakato . Dúvidas? Sugestões?

**Comment by ernegreiros** [comment]
sem duvidas

**Comment by ltakato** [comment]
@PePires58 @ernegreiros inciar partida é diferente de criar uma partida?
caso sim, acho legal que esse post esteja nesse endpoint separado de /iniciarPartida. caso não, acho interessante que aproveite o proprio POST mesmo do proprio recurso /partida mesmo sem colocar mais um endpoint.

**Comment by PePires58** [comment]
O correto seria criar uma partida, ou seja, registrar no banco.
Vou alterar o nome da rotina para deixar em inglês.

**Comment by PePires58** [comment]
@ltakato , @ernegreiros . Está sendo disponibilizado na issue #28 a continuação do cadastro da partida. Desse modo, evita ter que alterar oque já foi feito e deixa mais separado.

Issue encerrada.
