### ISSUE TITLE
[API] - Disponibilizar método para buscar partida atual

### ISSUE THREAD

**Issue by PePires58** [ernegreiros/BatalhaNaval#13]
Será disponibilizado uma rota para buscar a partida atual:
Rota: api/Match/CurrentMatch
Method: GET
**Objeto de entrada:** 
**Nenhum**

Objeto de retorno, quando sucesso:
<table>
<thead>
<tr>
<th>Nome da propriedade</th>
<th>Tipo de campo</th>
</tr>
<tbody>
<tr>
<td>ID</td>
<td>Int</td>
</tr>
<tr>
<td>Player1</td>
<td>Int</td>
</tr>
<tr>
<td>Player2</td>
<td>Int</td>
</tr>
<tr>
<td>MatchStatus</td>
<td>String</td>
</tr>
</tbody>
</table>

**Comment by PePires58** [comment]
@ernegreiros , @ltakato , dúvidas, sugestões?

**Comment by ernegreiros** [comment]
Uma sugestão seria criarmos uma camada de models pra modelagem dos objetos, e fazer isso antes da criação das rotas, discutimos no grupo

**Comment by PePires58** [comment]
@ernegreiros .
Estrutura no projeto **WEB**:
Models -> Nome do controler -> Entrada
Models -> Nome do controler -> Saida

Obs.: Todos os objetos de saída, herdam do objeto de base (OutBase).

Já disponível na master.

**Comment by ltakato** [comment]
@PePires58 @ernegreiros como se trata de um dado um pouco sensivel, sugiro que a gente pegue esse id do jogador pelo JWT, em vez de passar no body. inclusive como se trata de apenas uma "busca", seria ate legal que a gente conseguisse fazer de tudo pra ser um GET

**Comment by PePires58** [comment]
Beleza, entendi. Pode ser dessa forma. Ao invés de pegar pelo parâmetro pega do usuário autenticado.
