### ISSUE TITLE
[ARQUITETURA] realtime para sessoes de partidas

### ISSUE THREAD

**Issue by ltakato** [ernegreiros/BatalhaNaval#15]
![WhatsApp Image 2020-09-25 at 18 41 22](https://user-images.githubusercontent.com/17412678/94318448-faebfd80-ff5e-11ea-8809-d537f2730c14.jpeg)

sugestão de arquitetura de realtime para atender as partidas dos usuarios:
- toda vez que algum usuario executar alguma ação, o servidor recebe e envia como mensagem para outro jogador que esta conectado na hub da partida
- em paralelo, ja atualiza no banco esse evento (a ação do usuario no caso)

**Comment by PePires58** [comment]
Beleza, por mim pode ser assim. O @ernegreiros faz a parte do websoket e eu disponibilizo os métodos para o banco.

**Comment by ernegreiros** [comment]
PR https://github.com/ernegreiros/BatalhaNaval/pull/17

**Comment by ltakato** [comment]
arquitetura ja definida e em andamento (iniciado com o PR citado pelo @ernegreiros acima)
