### ISSUE TITLE
Ver critério de calculo de moeda do vencedor da partida

### ISSUE THREAD

**Issue by ltakato** [ernegreiros/BatalhaNaval#19]
Definimos que para aumentar engajamento e ter possibilidade de monetização, vamos trabalhar com "moedas" dentro do jogo.
Quando um jogador vence uma partida, tem que ter algum criterio de calculo a ser levado em consideração para ver "quantas moedas" o jogador vai ganhar

**Comment by julianababilon** [comment]
ganhar mais pontos quando ganha usando poderes seria uma maneira de incentivar o gasto de moedas por conta do retorno

**Comment by ltakato** [comment]
@julianababilon me parece interessante!!!
@PePires58 @ernegreiros se isso acontecer, é bom colocar no backoffice, o quanto de moedas o usuario vai ganhar "a mais", caso vença usando esse poder

**Comment by PePires58** [comment]
@ltakato , entendo!
1) Podemos colocar mais um campo de quanto ele ganha a mais se ganhar usando o poder.
2) Também seria interessante definir quanto ele ganha de dinheiro por partida ganha, também no backoffice.
2.1) Se ocorrer, abrir issue para contemplar rota e tela para essa implementação.

Por mim, ok.

E então?

- [x] @ernegreiros 

- [x] @ltakato 

- [x] @julianababilon

**Comment by julianababilon** [comment]
Por mim fechou assim, só definir a quantidade! pode ser um valor fixo ou valor relacionado ao quanto ele gastou com poder? tipo 50% cashback?

**Comment by PePires58** [comment]
@julianababilon . Fixo, para ficar mais fácil. Se concorda com os trechos acima. Marque seu check.

**Comment by julianababilon** [comment]
não to conseguindo dar check na caixa, estou dando ok por aqui!

**Comment by PePires58** [comment]
Conforme combinado, será fixo o valor de retorno por partida.
@julianababilon , de quanto seria? Favor abrir uma issue e nos informar.
