### ISSUE TITLE
[BE] Definir arquitetura da API

### ISSUE THREAD

**Issue by ernegreiros** [ernegreiros/BatalhaNaval#2]
Necessário abrir uma discussão de como faremos a API.
- [ ] O que precisaremos inicialmente
- [ ] Como estabelecer as partidas
- [ ] como criar a comunicação entre os jogadores

**Comment by PePires58** [comment]
Precisamos inicial: 
1) Criar um login para cada jogador e como se cadastrar 
2) Criar mecanismo de criar token para se comunicar com o front.
3) Estabelecer as partidas com uma tabela de partidas que tem dois jogadores em cada

**Comment by PePires58** [comment]
Fechar. Já alinhamos isso.

**Comment by ltakato** [comment]
issue encerrada dado que a estrutura do projeto foi definida!
