### ISSUE TITLE
Ideia de poderes

### ISSUE THREAD

**Issue by ltakato** [ernegreiros/BatalhaNaval#20]
Definimos que para atendermos essa parte de "inovação", vamos investir na parte de "poderes".
Algumas sugestões:
- de ataques: atingir 3 quadrados (em cubo, em linha), atingir uma cruz, escolher x lugares aleatorios...
- suporte: revelar area x do inimigo, recuperar area x danificada, proteger uma area x por uma rodada, mover

**Comment by ltakato** [comment]
outra ideia: jogar x vezes seguidos

**Comment by ltakato** [comment]
*vamos fechar padroes de poderes, e vamos tentar vende-los.
ex: de ataque x quadrados - x moedas, y quadrados - y moedas
ex: de proteger regiao - x quarados - x moedas, y quadrados - y moedas
ex: jogar x vezes seguidos - x moedas, y vezes seguidos - y moedas

**Comment by julianababilon** [comment]
Perfeito Leonardo!

**Comment by ltakato** [comment]
ideias de poderes fechadas! encerrando a issue!
