### ISSUE TITLE
Tela de cadasro de poderes

### ISSUE THREAD

**Issue by ltakato** [ernegreiros/BatalhaNaval#21]
*desenhar/definir (se basear na tela que ja ta feita da batalha, dos pixels)

**Comment by PePires58** [comment]
O cadastro se consiste em:
Nome do poder, tipo do poder (enum fixo), valor e um número que se ajusta de acordo com o tipo.
Ex.: Número quanto tipo for ataque: 1 representa (1x1), 2 representa (2x2).
Número quando tipo for número de jogadas seguidas: 1 (joga mais uma vez), 2 (joga mais duas vezes).

@ltakato @ernegreiros

**Comment by ltakato** [comment]
@PePires58 perfeito! inclusive voce ja resolveu um problema que estava pensando:
- se caso tivesse poder de ataque que permitisse (1x3) por exemplo? acho que nesse caso é melhor não ter, pra facilitar desenvolvimento mesmo! sempre vai fazendo em "cubos" (tanto o ataque, o de proteção, recuperação tambem)

**Comment by PePires58** [comment]
Favor abrir uma issue para corrigir o titulo da tela, apenas @ltakato
