### ISSUE TITLE
Login de superusuario (administrador do jogo)

### ISSUE THREAD

**Issue by ltakato** [ernegreiros/BatalhaNaval#22]
Fazer endpoint de login para o superusuario conseguir acessar o backoffice administrativo

**Comment by ltakato** [comment]
@PePires58 @ernegreiros ja meio que desenharam como seria a autenticação? como vai ser request, como vai ser response, se vai ser utilizado para proteger as rotas da api...

**Comment by PePires58** [comment]
Boa pergunta, @ltakato . Preciso saber como o react se comporta nessa. Consegue nos ajudar nessa questão? @ernegreiros

**Comment by ltakato** [comment]
@PePires58 o react em si ele não DITA como deve ser a autenticação. mas se voces conseguirem trabalhar com JWT acho que seria bacana, porque é padrao de mercado!

**Comment by ernegreiros** [comment]
Minha opinião, pra facilitar:
Cria uma rota pro cadastro do usuario:
- Recebe informações basicas 
{
       Name: (string) 
       Login: (string)
       Senha: (string) (antes de salvar no banco, encriptamos a string e salvamos o resultado)
       Money: (Preenchemos por padrão com os 1000)
} (de acordo com modelagem em https://github.com/ernegreiros/BatalhaNaval/issues/1)

Uma simples rota de login:
- Recebe um user e um password
{
       Login: (string)
       Senha: (string) 
}
Encriptamos a senha com o mesmo modo feito na rota de cadastro e comparamos o o login + senha criptografada, com o que temos no banco... não precisa ser nada muito complexo

**Comment by ernegreiros** [comment]
Fazer pelo jwt pode ser bacana tbm, mas não tenho experiencia com ele, nunca usei

**Comment by PePires58** [comment]
@ltakato , implementado pelo padrão JWT.
PR: https://github.com/ernegreiros/BatalhaNaval/pull/40

1) Solicitar token pela rota de auth
2) Enviar token via "Bearer"
