### ISSUE TITLE
[API] - Disponibilizar rota para cadastrar poder especial

### ISSUE THREAD

**Issue by PePires58** [ernegreiros/BatalhaNaval#23]
Será disponibilizado uma rota para o cadastro de poderes.
Rota: api/SpecialPower/
Method: POST
Objeto de entrada:

<table>
<thead>
<tr>
      <td>Nome da propriedade</td>
      <td>Tipo do campo </td>
      <td>Obrigatório?</td>
</tr>
</thead>
<tbody>
<tr>
      <td>Name</td>
      <td>string</td>
      <td>SIM</td>
</tr>
<tr>
      <td>Quantifier</td>
      <td>uint</td>
      <td>SIM</td>
</tr>
<tr>
      <td>Cost</td>
      <td>double</td>
      <td>SIM</td>
</tr>
<tr>
      <td>Type</td>
      <td>int (ENUM)</td>
      <td>SIM</td>
</tr>
</tbody>
</table>

Objeto de saída:
<table>
<thead>
<tr>
      <td>Nome da propriedade</td>
      <td>Tipo do campo </td>
</tr>
</thead>
<tbody>
<tr>
      <td>HttpStatus</td>
      <td>int</td>
</tr>
<tr>
      <td>Message</td>
      <td>string</td>
</tr>
</tbody>
</table>

Qualquer dúvida estou à disposição. @ltakato  @ernegreiros

**Comment by PePires58** [comment]
Rota criada e realizado o pull request, aguardando aceite de @ernegreiros .
Assim que realizar o merge, encerrar issue.

**Comment by ernegreiros** [comment]
Merge realizado
