### ISSUE TITLE
[Backend] - Criar dll Battleship.SpecialPower

### ISSUE THREAD

**Issue by PePires58** [ernegreiros/BatalhaNaval#24]
Criação inicial da dll de poder especial.

**Comment by PePires58** [comment]
Dll criada e realizado o pull request, aguardando aceite de @ernegreiros .
Assim que realizar o merge, encerrar issue.

**Comment by ernegreiros** [comment]
merge realizado

**Comment by ltakato** [comment]
@PePires58 tinha feito um comentario sobre mensagem de retorno quando dá erro estar em portugues em vez de ingles. mas ja que fez o merge, pode deixar. mas vamos tomar cuidado pra não ficar bagunçado
