### ISSUE TITLE
[API] - Adequação ao novo campo Compensation na rota de cadastrar poderes especiais

### ISSUE THREAD

**Issue by PePires58** [ernegreiros/BatalhaNaval#26]
Foi adicionado um novo campo:
<table>
<thead>
<tr>
<td>Propriedade</td>
<td>Tipo</td>
<td>Obrigatório?</td>
</tr>
</thead>
<tbody>
<tr>
<td>Compensation</td>
<td>Float</td>
<td>Sim</td>
</tr>
</tbody>
</table>

Vale lembrar que os demais dados estão na issue #23 

Qualquer dúvida estou a disposição @ltakato , @ernegreiros

**Comment by PePires58** [comment]
Ajuste feito, verificar PR e fechar issue.
@ltakato @ernegreiros

**Comment by ltakato** [comment]
#27 pullrequest aberdo do @PePires58 
dei uma olhada, me parece ok. estou um pouco perdido com a arquitetura do projeto, mas acho que só esperar o ok definitivo do @ernegreiros pra subir mesmo

**Comment by ernegreiros** [comment]
Pr avaliado
