### ISSUE TITLE
[API] - Disponibilizar método para cadastrar as posições no campo de batalha.

### ISSUE THREAD

**Issue by PePires58** [ernegreiros/BatalhaNaval#28]
Obs.: Essa rota deve ser usada em conjunto com a especificada na issue #12 

Será disponibilizado uma rota para iniciar a partida:
Rota: api/BattleField/RegisterPositions
Nome objeto do parâmetro: pModel
**Objeto de entrada: (ARRAY DE)** 

<table>
<thead>
<tr>
<th>Nome da propriedade</th>
<th>Tipo de campo</th>
<th>Obrigatório?</th>
</tr>
<tbody>
<tr>
<td>Player</td>
<td>Int</td>
<td>SIM</td>
</tr>
<tr>
<td>PosX</td>
<td>Int</td>
<td>SIM</td>
</tr>
<tr>
<td>PosY</td>
<td>Int</td>
<td>SIM</td>
</tr>
<tr>
<td>MatchId </td>
<td>Int</td>
<td>SIM</td>
</tr>
</tbody>
</table>

Objeto de retorno, quando sucesso:
<table>
<thead>
<tr>
<th>Nome da propriedade</th>
<th>Tipo de campo</th>
</tr>
<tbody>
<tr>
<td>HttpStatus</td>
<td>Int</td>
</tr>
<tr>
<td>Message</td>
<td>String</td>
</tr>
<tr>
</tbody>
</table>

@ernegreiros @ltakato . Dúvidas?

**Comment by PePires58** [comment]
Ajuste feito, verificar PR e fechar issue.
@ltakato @ernegreiros

**Comment by ltakato** [comment]
também tratando no PR #26
