### ISSUE TITLE
[BE] Utilizar o signalR como um websocket

### ISSUE THREAD

**Issue by ernegreiros** [ernegreiros/BatalhaNaval#3]
Pensar no uso de websocket pra controlar a comunicação entre os usuarios e lidar com as partidas.
é possivel lidar com as comunicações em tempo real, similar a um chatbot
https://docs.microsoft.com/pt-br/aspnet/core/tutorials/signalr

**Comment by ltakato** [comment]
@ernegreiros acho que signalR é uma otima saida, ainda mais que o nosso backend vai ser feito em .net! meu voto ja esta ganho!

**Comment by ernegreiros** [comment]
[Battleship.zip](https://github.com/ernegreiros/BatalhaNaval/files/5285514/Battleship.zip)

**Comment by ernegreiros** [comment]
PR https://github.com/ernegreiros/BatalhaNaval/pull/17

**Comment by ltakato** [comment]
sugestao aceita pelo time e já aplicado no projeto! 👍
